import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.shoppingitem.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl mx-auto my-12">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button type='button' className="bg-violet-500 transition hover:bg-violet-600 text-sm py-2 px-4 rounded-md text-white">Add Shopping Item</button>
        </div>
      </main>
    </>
  );
};

export default Home;
